set_attack_value(AT_DSTRONG, AG_SPRITE, sprite_get("dstrong"));
set_attack_value(AT_DSTRONG, AG_HURTBOX_SPRITE, sprite_get("dstrong_hurt"));
set_attack_value(AT_DSTRONG, AG_STRONG_CHARGE_WINDOW, 1);

set_attack_value(AT_DSTRONG, AG_NUM_WINDOWS, 5);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_LENGTH, 6);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_HAS_CUSTOM_FRICTION, 1);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_CUSTOM_GROUND_FRICTION, 0.2);

set_window_value(AT_DSTRONG, 2, AG_WINDOW_LENGTH, 6);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_SFX, sound_get("sfx_hammerswing_l"));
set_window_value(AT_DSTRONG, 2, AG_WINDOW_SFX_FRAME, 5);

set_window_value(AT_DSTRONG, 3, AG_WINDOW_LENGTH, 6);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_ANIM_FRAME_START, 4);

set_window_value(AT_DSTRONG, 4, AG_WINDOW_LENGTH, 4);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_ANIM_FRAME_START, 7);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSTRONG, 4, AG_WINDOW_SFX, sound_get("sfx_hammerswing_l"));
set_window_value(AT_DSTRONG, 4, AG_WINDOW_SFX_FRAME, 3);

set_window_value(AT_DSTRONG, 5, AG_WINDOW_LENGTH, 15);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_ANIM_FRAMES, 5);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_ANIM_FRAME_START, 9);
set_window_value(AT_DSTRONG, 5, AG_WINDOW_HAS_WHIFFLAG, 1);


set_num_hitboxes(AT_DSTRONG, 3);
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 1, HG_WINDOW, 3);
set_hitbox_value(AT_DSTRONG, 1, HG_LIFETIME, 2);
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_X, 50);
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_Y, -26);
set_hitbox_value(AT_DSTRONG, 1, HG_WIDTH, 80);
set_hitbox_value(AT_DSTRONG, 1, HG_HEIGHT, 52);
set_hitbox_value(AT_DSTRONG, 1, HG_PRIORITY, 4);
set_hitbox_value(AT_DSTRONG, 1, HG_DAMAGE, 11);
set_hitbox_value(AT_DSTRONG, 1, HG_ANGLE, 40);
set_hitbox_value(AT_DSTRONG, 1, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_DSTRONG, 1, HG_KNOCKBACK_SCALING, 1.15);
set_hitbox_value(AT_DSTRONG, 1, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DSTRONG, 1, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(AT_DSTRONG, 1, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_DSTRONG, 1, HG_HIT_SFX, sound_get("sfx_hammerhit_l"));
// set_hitbox_value(AT_DSTRONG, 1, HG_ANGLE_FLIPPER, 6);

/*set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 2, HG_WINDOW, 3);
set_hitbox_value(AT_DSTRONG, 2, HG_LIFETIME, 2);
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_X, 32);
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_Y, -26);
set_hitbox_value(AT_DSTRONG, 2, HG_WIDTH, 52);
set_hitbox_value(AT_DSTRONG, 2, HG_HEIGHT, 40);
set_hitbox_value(AT_DSTRONG, 2, HG_PRIORITY, 3);
set_hitbox_value(AT_DSTRONG, 2, HG_DAMAGE, 9);
set_hitbox_value(AT_DSTRONG, 2, HG_ANGLE, 45);
set_hitbox_value(AT_DSTRONG, 2, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DSTRONG, 2, HG_KNOCKBACK_SCALING, 1.1);
set_hitbox_value(AT_DSTRONG, 2, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DSTRONG, 2, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_DSTRONG, 2, HG_HIT_SFX, sound_get("sfx_hammerhit_m"));
set_hitbox_value(AT_DSTRONG, 2, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_DSTRONG, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 3, HG_WINDOW, 3);
set_hitbox_value(AT_DSTRONG, 3, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_DSTRONG, 3, HG_LIFETIME, 2);
set_hitbox_value(AT_DSTRONG, 3, HG_HITBOX_X, 32);
set_hitbox_value(AT_DSTRONG, 3, HG_HITBOX_Y, -32);
set_hitbox_value(AT_DSTRONG, 3, HG_WIDTH, 58);
set_hitbox_value(AT_DSTRONG, 3, HG_HEIGHT, 48);
set_hitbox_value(AT_DSTRONG, 3, HG_PRIORITY, 3);
set_hitbox_value(AT_DSTRONG, 3, HG_DAMAGE, 9);
set_hitbox_value(AT_DSTRONG, 3, HG_ANGLE, 135);
set_hitbox_value(AT_DSTRONG, 3, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DSTRONG, 3, HG_KNOCKBACK_SCALING, 1.1);
set_hitbox_value(AT_DSTRONG, 3, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DSTRONG, 3, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_DSTRONG, 3, HG_HIT_SFX, sound_get("sfx_hammerhit_m"));
set_hitbox_value(AT_DSTRONG, 3, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_DSTRONG, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 4, HG_WINDOW, 3);
set_hitbox_value(AT_DSTRONG, 4, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_DSTRONG, 4, HG_LIFETIME, 2);
set_hitbox_value(AT_DSTRONG, 4, HG_HITBOX_X, -32);
set_hitbox_value(AT_DSTRONG, 4, HG_HITBOX_Y, -32);
set_hitbox_value(AT_DSTRONG, 4, HG_WIDTH, 58);
set_hitbox_value(AT_DSTRONG, 4, HG_HEIGHT, 48);
set_hitbox_value(AT_DSTRONG, 4, HG_PRIORITY, 3);
set_hitbox_value(AT_DSTRONG, 4, HG_DAMAGE, 9);
set_hitbox_value(AT_DSTRONG, 4, HG_ANGLE, 135);
set_hitbox_value(AT_DSTRONG, 4, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DSTRONG, 4, HG_KNOCKBACK_SCALING, 1.1);
set_hitbox_value(AT_DSTRONG, 4, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DSTRONG, 4, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_DSTRONG, 4, HG_HIT_SFX, sound_get("sfx_hammerhit_m"));
set_hitbox_value(AT_DSTRONG, 4, HG_ANGLE_FLIPPER, 6);
*/
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 2, HG_WINDOW, 4);
set_hitbox_value(AT_DSTRONG, 2, HG_LIFETIME, 2);
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_X, -50);
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_Y, -26);
set_hitbox_value(AT_DSTRONG, 2, HG_WIDTH, 80);
set_hitbox_value(AT_DSTRONG, 2, HG_HEIGHT, 52);
set_hitbox_value(AT_DSTRONG, 2, HG_PRIORITY, 4);
set_hitbox_value(AT_DSTRONG, 2, HG_DAMAGE, 11);
set_hitbox_value(AT_DSTRONG, 2, HG_ANGLE, 140);
set_hitbox_value(AT_DSTRONG, 2, HG_BASE_KNOCKBACK, 7);
set_hitbox_value(AT_DSTRONG, 2, HG_KNOCKBACK_SCALING, 1.15);
set_hitbox_value(AT_DSTRONG, 2, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DSTRONG, 2, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(AT_DSTRONG, 2, HG_VISUAL_EFFECT, 304);
set_hitbox_value(AT_DSTRONG, 2, HG_HIT_SFX, sound_get("sfx_hammerhit_l"));
// set_hitbox_value(AT_DSTRONG, 5, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_DSTRONG, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 3, HG_WINDOW, 5);
set_hitbox_value(AT_DSTRONG, 3, HG_LIFETIME, 2);
set_hitbox_value(AT_DSTRONG, 3, HG_HITBOX_X, 50);
set_hitbox_value(AT_DSTRONG, 3, HG_HITBOX_Y, -26);
set_hitbox_value(AT_DSTRONG, 3, HG_WIDTH, 80);
set_hitbox_value(AT_DSTRONG, 3, HG_HEIGHT, 52);
set_hitbox_value(AT_DSTRONG, 3, HG_PRIORITY, 4);
set_hitbox_value(AT_DSTRONG, 3, HG_DAMAGE, 9);
set_hitbox_value(AT_DSTRONG, 3, HG_ANGLE, 40);
set_hitbox_value(AT_DSTRONG, 3, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_DSTRONG, 3, HG_KNOCKBACK_SCALING, 1.1);
set_hitbox_value(AT_DSTRONG, 3, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_DSTRONG, 3, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(AT_DSTRONG, 3, HG_VISUAL_EFFECT, 301);
set_hitbox_value(AT_DSTRONG, 3, HG_HIT_SFX, sound_get("sfx_hammerhit_m"));
/*
set_hitbox_value(AT_DSTRONG, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 6, HG_WINDOW, 4);
set_hitbox_value(AT_DSTRONG, 6, HG_LIFETIME, 2);
set_hitbox_value(AT_DSTRONG, 6, HG_HITBOX_X, -32);
set_hitbox_value(AT_DSTRONG, 6, HG_HITBOX_Y, -26);
set_hitbox_value(AT_DSTRONG, 6, HG_WIDTH, 52);
set_hitbox_value(AT_DSTRONG, 6, HG_HEIGHT, 40);
set_hitbox_value(AT_DSTRONG, 6, HG_PRIORITY, 3);
set_hitbox_value(AT_DSTRONG, 6, HG_DAMAGE, 9);
set_hitbox_value(AT_DSTRONG, 6, HG_ANGLE, 135);
set_hitbox_value(AT_DSTRONG, 6, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DSTRONG, 6, HG_KNOCKBACK_SCALING, 1.1);
set_hitbox_value(AT_DSTRONG, 6, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DSTRONG, 6, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_DSTRONG, 6, HG_HIT_SFX, sound_get("sfx_hammerhit_m"));
set_hitbox_value(AT_DSTRONG, 6, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_DSTRONG, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 7, HG_WINDOW, 4);
set_hitbox_value(AT_DSTRONG, 7, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_DSTRONG, 7, HG_LIFETIME, 2);
set_hitbox_value(AT_DSTRONG, 7, HG_HITBOX_X, 32);
set_hitbox_value(AT_DSTRONG, 7, HG_HITBOX_Y, -26);
set_hitbox_value(AT_DSTRONG, 7, HG_WIDTH, 58);
set_hitbox_value(AT_DSTRONG, 7, HG_HEIGHT, 48);
set_hitbox_value(AT_DSTRONG, 7, HG_PRIORITY, 3);
set_hitbox_value(AT_DSTRONG, 7, HG_DAMAGE, 9);
set_hitbox_value(AT_DSTRONG, 7, HG_ANGLE, 35);
set_hitbox_value(AT_DSTRONG, 7, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DSTRONG, 7, HG_KNOCKBACK_SCALING, 1.1);
set_hitbox_value(AT_DSTRONG, 7, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DSTRONG, 7, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_DSTRONG, 7, HG_HIT_SFX, sound_get("sfx_hammerhit_l"));
set_hitbox_value(AT_DSTRONG, 7, HG_ANGLE_FLIPPER, 6);

set_hitbox_value(AT_DSTRONG, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 8, HG_WINDOW, 4);
set_hitbox_value(AT_DSTRONG, 8, HG_LIFETIME, 2);
set_hitbox_value(AT_DSTRONG, 8, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(AT_DSTRONG, 8, HG_HITBOX_X, 24);
set_hitbox_value(AT_DSTRONG, 8, HG_HITBOX_Y, -26);
set_hitbox_value(AT_DSTRONG, 8, HG_WIDTH, 52);
set_hitbox_value(AT_DSTRONG, 8, HG_HEIGHT, 40);
set_hitbox_value(AT_DSTRONG, 8, HG_PRIORITY, 3);
set_hitbox_value(AT_DSTRONG, 8, HG_DAMAGE, 9);
set_hitbox_value(AT_DSTRONG, 8, HG_ANGLE, 45);
set_hitbox_value(AT_DSTRONG, 8, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DSTRONG, 8, HG_KNOCKBACK_SCALING, 1.1);
set_hitbox_value(AT_DSTRONG, 8, HG_BASE_HITPAUSE, 8);
set_hitbox_value(AT_DSTRONG, 8, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_DSTRONG, 8, HG_HIT_SFX, sound_get("sfx_hammerhit_m"));
set_hitbox_value(AT_DSTRONG, 8, HG_ANGLE_FLIPPER, 6);
*/